modules:
  - module_type: llama_index_chunk
    chunk_method: Token
    chunk_size: [ 1024, 512 ]
    chunk_overlap: 24
  - module_type: llama_index_chunk
    chunk_method: [ SentenceWindow ]
    sentence_splitter: kiwi
  - module_type: langchain_chunk
    chunk_method: character
