modules:
  - module_type: llama_index_chunk
    chunk_method: [ Token ]
    chunk_size: [ 512 ]
    chunk_overlap: 24
    add_file_name: ko
  - module_type: llama_index_chunk
    chunk_method: [ SentenceWindow ]
    window_size: 3
    add_file_name: ko
